version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: joan-ximo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "#2daw_JX"
    volumes:
      - ./database:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - rdp
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: joan_ximo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "#2daw_JX"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - rdp
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: root
      GF_SECURITY_ADMIN_PASSWORD: "#2daw_JX"
    networks:
      - rdp
networks:
  rdp:
