version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: electrobike
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "#2daw_JX"
    volumes:
      - ./database:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    networks:
      - rdp
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: joan_ximo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "#2daw_JX"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - rdp
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  django:
    build: ./backend
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./backend/electrobike:/opt/app/electrobike
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rdp

networks:
  rdp:
