# Generated by Django 3.2.16 on 2023-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id_station', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('img', models.TextField()),
            ],
        ),
    ]
