# Generated by Django 3.2.16 on 2023-01-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='station',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
