# Generated by Django 3.2.16 on 2023-01-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='stations',
        ),
    ]
