# Generated by Django 3.2.18 on 2023-02-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
                ('img', models.TextField(blank=True, default='https://cdn-icons-png.flaticon.com/512/665/665049.png', null=True)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
