# Generated by Django 3.2.18 on 2023-02-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '__first__'),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id_slot', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0, unique=True)),
                ('bike', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bikes.bike')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
    ]
