# Generated by Django 3.2.16 on 2023-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slug',
        ),
        migrations.AddField(
            model_name='slot',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
