# Generated by Django 3.2.16 on 2023-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
