# Generated by Django 3.2.17 on 2023-02-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='charge',
            new_name='role',
        ),
    ]
