# Generated by Django 3.2.16 on 2023-02-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bike', 'Bike'), ('slot', 'Slot'), ('station', 'Station')], max_length=100)),
                ('id_type', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
    ]
