# Generated by Django 3.2.17 on 2023-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='get_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
