# Generated by Django 3.2.18 on 2023-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id_bike', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('bike_plate', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'bikes',
            },
        ),
    ]
